// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjP0vT5TajpNN35n5bXobYvYHPuKTRlY4',
    appId: '1:57330914362:web:0069ba8de9e1cff9861103',
    messagingSenderId: '57330914362',
    projectId: 'kyrgyz-til-play',
    authDomain: 'kyrgyz-til-play.firebaseapp.com',
    storageBucket: 'kyrgyz-til-play.firebasestorage.app',
    measurementId: 'G-JM2L2DEV7C',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjP0vT5TajpNN35n5bXobYvYHPuKTRlY4',
    appId: '1:57330914362:web:b01aad0ccdda2eac861103',
    messagingSenderId: '57330914362',
    projectId: 'kyrgyz-til-play',
    authDomain: 'kyrgyz-til-play.firebaseapp.com',
    storageBucket: 'kyrgyz-til-play.firebasestorage.app',
    measurementId: 'G-3XF7BXZCX2',
  );
}
